---
title: "iteration"
author: "Hannah Bowlin"
date: "10/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
set.seed(1)

```

# Get Started

```{r}
x = rnorm(30, mean = 4, sd = 2.3)
x_again = rnorm(25, mean = 4, sd = 2.5)
y = rnorm(20, mean = 5, sd = 2)

# z scores for this vector
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  z
  
}

z_scores(x)
```

# Creating the function

```{r}
z_scores = function(x_arg) {
  
  z = (x_arg - mean(x_arg)) / sd(x_arg)
  z
  
}

z_scores(x)
```

```{r}
z_scores(x_arg = x)

z_scores(x_arg = y)
```


```{r}
# doesnt work always for charcter vectors or factors
z_scores(x_arg = 3)
# z_scores(x = "my name is hannah")
z_scores(x_arg = c(TRUE, TRUE , FALSE, TRUE))
```

# Conditional execution

```{r}
z_scores = function(x_arg) {
  
  if (!is.numeric(x_arg)) {
    stop("Argument x should be numeric")
  } else if (length(x_arg) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = mean(x) / sd(x)
  
  z
}
```

## Multiple outputs

```{r}
mean_and_sd = function(x_arg) {
  
  if (!is.numeric(x_arg)) {
    stop("Argument x should be numeric")
  } else if (length(x_arg) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x_arg)
  sd_x = sd(x_arg)

  list(mean = mean_x, 
       sd = sd_x)
}
```

```{r}
mean_and_sd = function(x_arg) {
  
  if (!is.numeric(x_arg)) {
    stop("Argument x should be numeric")
  } else if (length(x_arg) < 3) {
    stop("x should be longer than 3")
  }
  
  mean_x = mean(x_arg)
  sd_x = sd(x_arg)

  list(mean = mean_x, 
       sd = sd_x)
}
```


```{r}
mean_and_sd = function(x_arg) {
  
  if (!is.numeric(x_arg)) {
    stop("Argument x should be numeric")
  } else if (length(x_arg) < 3) {
    stop("x should be longer than 3")
  }
  
  mean_x = mean(x_arg)
  sd_x = sd(x_arg)

  list(mean = mean_x, 
       sd = sd_x,
       z_scores = (x_arg - mean(x_arg)) / sd(x_arg))
}
```
```{r}
mean_and_sd = function(x_arg) {
  
  if (!is.numeric(x_arg)) {
    stop("Argument x should be numeric")
  } else if (length(x_arg) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x_arg)
  sd_x = sd(x_arg)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

# Multiple Inputs

## Linear regression, beta0_hat is the beta coefficient
```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]

sim_data %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = 2 + 3 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}
```

```{r}
sim_regression(n = 30)
sim_regression(n = 3000)
```

